### ISSUE TITLE
Document configuration class more thoroughly

### ISSUE THREAD

**Issue by f4n** [nightowlengineer/sonos-api-java#3]
**Describe what's going wrong**
Couln't use the library: "Invalid token". Please describe what the sonos applicationId is. Do we need other settings e.g. event callback url or something else?

**Log**
```
15:25:09.713 INFO  [main] e.nightowl.sonos.api.SonosApiClient - Initialising sonos-api-java:0.0.9
15:25:09.717 DEBUG [main] e.nightowl.sonos.api.SonosApiClient - Using default HttpClient
15:25:10.161 DEBUG [main] e.n.sonos.api.resource.GroupResource - Sending request to https://api.ws.sonos.com/control/api/v1/households/householdId/groups
Exception in thread "main" engineer.nightowl.sonos.api.exception.SonosApiClientException: Invalid token
	at engineer.nightowl.sonos.api.resource.BaseResource.callApi(BaseResource.java:81)
	at engineer.nightowl.sonos.api.resource.BaseResource.getFromApi(BaseResource.java:178)
	at engineer.nightowl.sonos.api.resource.GroupResource.getGroups(GroupResource.java:51)
	at SonosTest.main(SonosTest.java:21)
```

**Comment by nightowlengineer** [comment]
It's just the GUID for the integration you've created on the Sonos Developer portal. It isn't used in the creation of the token etc, just there for convenience.

The error you're getting, makes it sound like you haven't set the keys up correctly or haven't authorised your integration properly. If you can show some example code etc I can try and help diagnose what's going wrong.
